'use strict';
// Real Babylon/WebGL overlay test. Supply BABYLON_BUNDLE and CHROMIUM_EXECUTABLE.
// The background deliberately uses Roll20's alpha render queue: opaque-queue
// attack meshes disappear behind it, even if the JavaScript geometry is valid.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),A=require('../extension/firefox/beta/attack-map.js');
(async()=>{assert.ok(process.env.BABYLON_BUNDLE,'BABYLON_BUNDLE must point to babylon.js');const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:512,height:512}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<style>body{margin:0}</style><canvas id="map" width="512" height="512"></canvas>');await page.addScriptTag({path:process.env.BABYLON_BUNDLE});
let positions=[],indices=[];for(let q=-8;q<9;q++)for(let r=-8;r<9;r++){let p=A.basis({flat:true,radius:40},q,r),corners=A.polygon({flat:true,radius:40/.98},p[0]+11,p[1]+22);for(let i=0;i<6;i++){let n=positions.length/3,a=corners[i],b=corners[(i+1)%6];positions.push(a[0],-a[1],0,b[0],-b[1],0);indices.push(n,n+1);}}
await page.evaluate(({positions,indices,numeric})=>{const B=BABYLON,engine=new B.Engine(document.querySelector('canvas'),false,{preserveDrawingBuffer:true,stencil:true}),scene=window.MeshScene=new B.Scene(engine);scene.clearColor=new B.Color4(.1,.2,.3,1);const camera=new B.FreeCamera('camera',new B.Vector3(40,0,110),scene);camera.setTarget(new B.Vector3(40,0,100));camera.mode=B.Camera.ORTHOGRAPHIC_CAMERA;camera.orthoLeft=-160;camera.orthoRight=160;camera.orthoBottom=-160;camera.orthoTop=160;camera.minZ=.1;camera.maxZ=50;
const grid=new B.Mesh('Hex-Grid-Line-System',scene);grid.setVerticesData('position',positions);grid.setIndices(indices);grid.position.z=100;grid.alphaIndex=10;grid.computeWorldMatrix(true);grid.setEnabled(false);
const material=new B.ShaderMaterial('map-background',scene,{vertexSource:'precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;void main(){gl_Position=worldViewProjection*vec4(position,1.0);}',fragmentSource:'precision highp float;void main(){gl_FragColor=vec4(0.1,0.2,0.3,1.0);}'},{attributes:['position'],uniforms:['worldViewProjection'],needAlphaBlending:true});material.alpha=.999;material.disableDepthWrite=true;material.backFaceCulling=false;let background=B.Mesh.CreatePlane('background',400,scene);background.position.z=99;background.alphaIndex=0;background.material=material;
const node=new B.TransformNode('t1-markers',scene);node.position=new B.Vector3(71,82,100);const token=window.testToken={id:'t1',attributes:{left:numeric?11:'11',top:numeric?22:'22',layer:'objects',statusmarkers:'',controlledby:'all'},get(k){return this.attributes[k]},save(d){Object.assign(this.attributes,d)}};const pg={id:'page',thegraphics:{models:[token],get:()=>token},get(k){return {showgrid:true,grid_type:'hexr',width:20,height:20,snapping_increment:1}[k]}};window.Campaign={activePage:()=>pg};window.currentPlayer={id:'p1',d20:{engine:{tabletopSelected:()=>[{model:token}]}}};window.is_gm=false;window.testEngine=engine;engine.runRenderLoop(()=>scene.render());},{positions,indices,numeric:!!process.env.ROLL20_NUMERIC_COORDS});
await page.addScriptTag({path:process.env.ATTACK_MAP_SOURCE||path.join(root,'extension/firefox/beta/attack-map.js')});await page.evaluate(()=>OwdAttackMap.preview(window,{sequence:1,preview:{mirror:false,orientation:0,path:[[0,-1,'hit'],[1,-1,'pass']],owner:'webgl-test',expiresAt:Date.now()+15000}}));await page.waitForFunction(()=>__owdAttackMapState.cells[0]?.cells.length===2,{},{timeout:5000});await page.waitForFunction(()=>MeshScene.meshes.filter(m=>m.name.startsWith('owd-attack-cell-')).every(m=>m.material.isReady(m)));
const result=await page.evaluate(async()=>{for(let i=0;i<4;i++){MeshScene.render();await new Promise(requestAnimationFrame);}let pixels=await testEngine.readPixels(0,0,512,512),gold=0,pass=0;for(let i=0;i<pixels.length;i+=4){if(pixels[i]===255&&pixels[i+1]===215&&pixels[i+2]===127)gold++;if(pixels[i]===103&&pixels[i+1]===91&&pixels[i+2]===65)pass++;}let empty=__owdAttackMapState.cells[0].cells.every(c=>{let p=BABYLON.Vector3.Project(new BABYLON.Vector3(c.x,-c.y,98),BABYLON.Matrix.Identity(),MeshScene.getTransformMatrix(),MeshScene.activeCamera.viewport.toGlobal(512,512)),i=(Math.floor(512-p.y)*512+Math.floor(p.x))*4;return Math.abs(pixels[i]-26)<=1&&Math.abs(pixels[i+1]-51)<=1&&Math.abs(pixels[i+2]-77)<=1;});return {gold,pass,empty,materials:MeshScene.meshes.filter(m=>m.name.startsWith('owd-attack-cell-')).map(m=>({blend:m.material.needAlphaBlending(),alpha:m.material.alpha}))};});console.log(JSON.stringify(result));assert.ok(result.gold>100&&result.pass>100,'both opaque sheet colours must actually render over the map');assert.equal(result.empty,true,'cell interiors must leave the map visible');assert.ok(result.materials.every(m=>m.blend&&m.alpha===1));assert.deepEqual(errors,[]);await page.screenshot({path:process.env.ATTACK_MAP_SCREENSHOT||'/tmp/owd-attack-webgl.png'});console.log('OK WebGL Babylon réel : contours visibles au-dessus de la carte, intérieurs vides, deux teintes opaques et coordonnées texte');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
