'use strict';
const {chromium,firefox}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const M=require('../docs/javascripts/owd-attr-map.js'),C=require('../docs/javascripts/owd-sync.js'),A=require('../extension/firefox/beta/attack-map.js');
const root=path.resolve(__dirname,'..'),states={},token={id:'t1',left:400,top:400,width:70,height:70,layer:'objects',controlledby:'all',statusmarkers:'red@2',represents:'hero'};let writes=[],chats=[];
let s=M.blank();s.v=M.SCHEMA;s.rel=M.release();s.name='Hero';s.inv.objets=[{ref:'blade',nom:'Dague',qte:1,ou:'sac',arme:{type:'dague',attaque:6,degats:16}}];s.attaques=[{id:'a1',arme:'blade'}];states.hero={[C.BASE]:{current:JSON.stringify({format:1,state:s}),max:''},owd_version:{current:String(M.SCHEMA),max:M.release()},owd_state:{current:JSON.stringify(s),max:''}};
function harness(){return `<!doctype html><meta charset="utf-8"><style>body{margin:0}#master-toolbar{position:fixed;width:40px;height:100vh;z-index:20}.toolbar-button-outer{height:32px}.icon-slot{width:30px;height:30px}#babylonCanvas{position:fixed;left:40px;top:0;width:1000px;height:850px}#rightsidebar{position:fixed;right:0;width:180px;height:100vh}</style><link rel="stylesheet" href="/ext/overlay.css"><canvas id="babylonCanvas" width="1000" height="850"></canvas><div id="master-toolbar"><div class="upper-buttons"><div class="spacer-outer"><div class="spacer-header">TOOLS</div></div><div class="toolbar-button-outer"><div class="icon-slot">X</div></div><div id="more-tools-button"></div></div></div><div id="rightsidebar"><div id="textchat-input"><textarea></textarea><button>send</button></div></div><script>
window.is_gm=false;window.currentPlayer={id:'p1'};window.selected=true;window.gridRadius=40;window.gridFlat=true;window.origin=[11,22];
const tok={id:'t1',attributes:{},get(k){return this.attributes[k]},save(d){Object.assign(this.attributes,d);backend({kind:'token-write',data:d})}};
const col={models:[tok],get:id=>id==='t1'?tok:null};const pg={id:'p1',thegraphics:col,get(k){return {grid_type:gridFlat?'hexr':'hex',showgrid:true,snapping_increment:gridRadius/40,width:20,height:20}[k]}};
function attr(data){return {attributes:{...data},get(k){return this.attributes[k]},set(d){Object.assign(this.attributes,d)},save(_,opts){backend({kind:'write',data:this.attributes}).then(()=>opts&&opts.success&&opts.success())}}}
const attrs={models:[],create(d){let m=attr(d);this.models.push(m);return m},fetch(opts){backend({kind:'read'}).then(a=>{this.models=Object.keys(a).map(n=>attr({name:n,...a[n]}));opts&&opts.success&&opts.success()})}};
const ch={id:'hero',attribs:attrs,get(k){return k==='name'?'Hero':k==='controlledby'?'all':''}};window.Campaign={id:'test',characters:{models:[ch],get:id=>id==='hero'?ch:null},players:{models:[]},activePage:()=>pg};
const tokenObject={model:tok,visible:true,left:400,top:400,width:70,height:70};window.currentPlayer.d20={engine:{tabletopSelected:()=>selected?[{id:'t1',model:tok}]:[],canvasZoom:1,currentCanvasOffset:[0,0],canvas:{lowerCanvasEl:document.querySelector('canvas'),getObjects:()=>[tokenObject]}},canvas_overlay:{drawGrid(ctx){let R=gridRadius,S=Math.sqrt(3);for(let q=-8;q<14;q++)for(let r=-8;r<14;r++){let x=origin[0]+(gridFlat?1.5*R*q:S*R*(q+r/2)),y=origin[1]+(gridFlat?S*R*(r+q/2):1.5*R*r);for(let i=0;i<6;i++){let a=(60*i+(gridFlat?0:30))*Math.PI/180,b=(60*(i+1)+(gridFlat?0:30))*Math.PI/180;ctx.moveTo(x+R*Math.cos(a),y+R*Math.sin(a));ctx.lineTo(x+R*Math.cos(b),y+R*Math.sin(b));}ctx.stroke();}}}};
window.moveToken=(x,y)=>{tokenObject.left=x;tokenObject.top=y;tok.attributes.left=x;tok.attributes.top=y;backend({kind:'token-write',data:{left:x,top:y}})};
async function update(){let t=await backend({kind:'token-read'});Object.assign(tok.attributes,t);tokenObject.left=t.left;tokenObject.top=t.top}setInterval(update,100);
document.querySelector('#textchat-input button').onclick=()=>{backend({kind:'chat',text:document.querySelector('textarea').value});document.querySelector('textarea').value=''};
Promise.all([update(),backend({kind:'read'}).then(a=>{attrs.models=Object.keys(a).map(n=>attr({name:n,...a[n]}));})]).then(()=>{let e=document.createElement('script');e.src='/ext/beta/content-roll20.js';document.body.appendChild(e)});
</script>`;}
const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://localhost'),file,data;if(u.pathname==='/editor'){file='index.html';data=harness();}else{let ext=u.pathname.startsWith('/ext/');file=path.join(root,ext?'extension/firefox':'site',decodeURIComponent(ext?u.pathname.slice(5):u.pathname));if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}data=fs.readFileSync(file);}res.writeHead(200,{'content-type':file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'text/html'});res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let url='http://127.0.0.1:'+server.address().port,b=await (process.env.TEST_BROWSER==='firefox'?firefox:chromium).launch({headless:true,...(process.env.TEST_BROWSER==='firefox'?{}:{executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']})});try{let ctx=await b.newContext({viewport:{width:1400,height:900}}),errors=[];
await ctx.exposeBinding('backend',async(_,m)=>{if(m.kind==='read')return C.copy(states.hero);if(m.kind==='write'){states.hero[m.data.name]={current:m.data.current,max:m.data.max};return;}if(m.kind==='token-read')return {...token};if(m.kind==='token-write'){Object.assign(token,m.data);writes.push({...m.data});return;}if(m.kind==='chat')chats.push(m.text)});
await ctx.addInitScript(({url})=>{window.browser={runtime:{getURL:p=>url+'/ext/'+p},storage:{local:{get:async()=>({owdBeta:true,owdNuit:'nuit',owd_site_url:url.replace('127.0.0.1','localhost')+'/'}),set:async()=>{}},onChanged:{addListener(){}}}}},{url});
let a=await ctx.newPage(),bpage=await ctx.newPage();[a,bpage].forEach(p=>p.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)}));await Promise.all([a.goto(url+'/editor'),bpage.goto(url+'/editor')]);await bpage.waitForFunction(()=>!!window.OwdAttackMap);assert.equal(bpage.frames().length,1);console.log('OK réception active sans fiche ni panneau ouvert');
await a.locator('#owd-outil-attaques').click();let tabs;for(let i=0;i<100;i++){tabs=a.frames().find(f=>f.url().includes('/roll20-attaques.html'));if(tabs&&await tabs.locator('select option').count())break;await a.waitForTimeout(100);}await tabs.locator('select').selectOption('hero');let sheet=tabs.frameLocator('.inventaire-active');await sheet.locator('.pc-attaque-tete').click();await sheet.locator('.pc-attaque-coup').first().hover();await bpage.waitForFunction(()=>window.__owdAttackMapState.cells.length>0);
let preview=A.decode(token.statusmarkers.split(',').find(t=>t.startsWith('owd-atk-')));assert.deepEqual(preview.path,[[0,-1,'hit']]);assert.equal(preview.orientation,0);assert.ok(token.statusmarkers.includes('red@2'));assert.equal(await bpage.locator('#owd-attack-map').count(),1);console.log('OK survol natif cross-origin, statusmarkers partagé, cases sur les deux clients');
let ink=await bpage.evaluate(()=>{let c=document.querySelector('#owd-attack-map'),ctx=c.getContext('2d'),p=__owdAttackMapState.cells[0].cells[0],data=ctx.getImageData(0,0,c.width,c.height).data;return {centre:ctx.getImageData(Math.round(p.x),Math.round(p.y),1,1).data[3],gold:Array.from({length:data.length/4},(_,i)=>i*4).some(i=>data[i]===255&&data[i+1]===215&&data[i+2]===127&&data[i+3]===255)};});assert.equal(ink.centre,0);assert.equal(ink.gold,true);console.log('OK intérieur vide et contour doré entièrement opaque');
let before=await bpage.evaluate(()=>__owdAttackMapState.cells[0].cells[0]);await a.evaluate(()=>moveToken(520,480));await bpage.waitForFunction(()=>__owdAttackMapState.cells[0].cells[0].x>450);let after=await bpage.evaluate(()=>__owdAttackMapState.cells[0].cells[0]);assert.notEqual(before.x,after.x);
await bpage.evaluate(()=>{currentPlayer.d20.engine.canvasZoom=1.5;currentPlayer.d20.engine.currentCanvasOffset=[100,100]});await bpage.screenshot({path:'/tmp/owd-attack-map.png'});assert.equal(await bpage.locator('#owd-attack-map').evaluate(c=>getComputedStyle(c).pointerEvents),'none');console.log('OK déplacement, grille alignée, zoom/décalage, calque non interactif');
await a.mouse.move(1200,800);await bpage.waitForFunction(()=>__owdAttackMapState.cells.length===0);assert.equal(token.statusmarkers,'red@2');
await sheet.locator('.pc-attaque-orientation').selectOption('2');await sheet.locator('.pc-attaque-miroir').click();await sheet.locator('.pc-attaque-coup').nth(1).hover();await bpage.waitForFunction(()=>__owdAttackMapState.cells.length>0);preview=A.decode(token.statusmarkers.split(',').find(t=>t.startsWith('owd-atk-')));assert.equal(preview.orientation,2);assert.equal(preview.mirror,true);assert.equal(preview.path.length,2);console.log('OK miroir et orientation envoyés avec trajet droitier normal');
await a.locator('#owd-outil-attaques').click();await bpage.waitForFunction(()=>__owdAttackMapState.cells.length===0);assert.equal(token.statusmarkers,'red@2');console.log('OK fermeture du panneau retire le marqueur');
await a.locator('#owd-outil-attaques').click();await sheet.locator('.pc-attaque-coup').first().hover();await bpage.waitForFunction(()=>__owdAttackMapState.cells.length>0);await a.evaluate(()=>selected=false);await bpage.waitForFunction(()=>__owdAttackMapState.cells.length===0);assert.equal(token.statusmarkers,'red@2');await a.mouse.move(1200,800);await a.evaluate(()=>selected=true);console.log('OK désélection retire le marqueur');
// Arbitrary-range payload also accepted through the real bound bridge.
let sf=a.frames().find(f=>f.url().includes('/roll20-fiche.html'));await sf.evaluate(()=>__owdAttackPreview({mirror:false,orientation:0,path:[[0,-1,'pass'],[0,-6,'hit'],[2,-7,'hit']]}));await bpage.waitForFunction(()=>__owdAttackMapState.cells[0]?.cells.length===3);assert.equal((await bpage.evaluate(()=>__owdAttackMapState.cells[0].cells)).some(c=>c.r===-6),true);console.log('OK portée six et branche distante partagées');
await sf.evaluate(()=>__owdAttackPreview(null));await bpage.waitForFunction(()=>__owdAttackMapState.cells.length===0);
// Receiver expiration works even when the source is gone.
let exp={mirror:false,orientation:0,path:[[0,-1,'hit']],owner:'gone',expiresAt:Date.now()+900};token.statusmarkers='red@2,'+A.encode(exp);await bpage.waitForFunction(()=>__owdAttackMapState.cells.length>0);await bpage.waitForFunction(()=>__owdAttackMapState.cells.length===0);token.statusmarkers='red@2';console.log('OK expiration d’un aperçu orphelin');
await a.evaluate(()=>{Campaign.activePage().thegraphics.models[0].attributes.controlledby='p2';Campaign.characters.models[0].get=k=>k==='controlledby'?'p2':'Hero'});await sf.evaluate(()=>__owdAttackPreview({mirror:false,orientation:0,path:[[0,-1,'hit']]}));await a.waitForTimeout(1500);assert.equal(token.statusmarkers,'red@2');await sf.evaluate(()=>__owdAttackPreview(null));assert.equal(chats.length,0);assert.deepEqual(errors,[]);assert.equal(await bpage.evaluate(()=>__owdAttackMapState.error),null);console.log('OK droits revérifiés, aucun jet ni dégâts envoyés par le survol, aucune erreur');
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
