'use strict';
const assert=require('node:assert/strict'),D=require('../docs/javascripts/owd-monde-data.js'),C=D.sync,F=require('../docs/javascripts/owd-sync.js');
let total=0;function test(n,f){f();total++;console.log('OK '+n);}
const empty={v:1,horloge:{jours:1,heures:8,minutes:0,secondes:0},temperature:20};
const attrs=s=>({[C.BASE]:{current:JSON.stringify({format:1,state:s}),max:''}});
function merge(store,lot){Object.assign(store,lot);}
test('horloge : reports secondes/minutes/heures vers les jours',()=>assert.deepEqual(D.clock({jours:2,heures:25,minutes:61,secondes:61}),{jours:3,heures:2,minutes:2,secondes:1}));
test('horloge : round de 3 s, minuit, recul sans temps négatif',()=>{assert.deepEqual(D.advance({jours:12,heures:23,minutes:59,secondes:59},3),{jours:13,heures:0,minutes:0,secondes:2});assert.deepEqual(D.advance(empty.horloge,-999999),{jours:0,heures:0,minutes:0,secondes:0});});
test('conversion Camp : date et température manuelle conservées',()=>assert.deepEqual(D.read({owd_camp_h:{current:'5,1430'},owd_camp_conf:{current:'{"v":1,"degres":-12,"lieu":"Berg"}'}}),{v:1,horloge:{jours:5,heures:23,minutes:50,secondes:0},temperature:-12}));
test('conversion Camp : température calculée avant conversion conservée',()=>{assert.equal(D.read({owd_camp_h:'3,60',owd_camp_conf:'{"v":1,"milieu":"desert"}'}).temperature,18);assert.equal(D.read({owd_camp_h:'3,480',owd_camp_conf:'{"v":1,"milieu":"desert"}'}).temperature,42);});
test('Camp neuf : premier jour à 8 h, température inconnue',()=>{assert.equal(D.read({}).temperature,null);assert.equal(D.read({}).horloge.heures,8);});
test('horloge et température simultanées : aucun écrasement',()=>{const s=attrs(empty),a=new C.Session(s,empty),b=new C.Session(s,empty),sa=C.copy(empty),sb=C.copy(empty);sa.horloge=D.advance(sa.horloge,3600);sb.temperature=-5;a.capture(sa);b.capture(sb);const la=a.outgoing(),lb=b.outgoing();assert.equal(Object.keys(la).length,1);assert.equal(Object.keys(lb).length,1);merge(s,la);merge(s,lb);assert.deepEqual(a.receive(s).state,b.receive(s).state);assert.equal(D.read(s).temperature,-5);assert.equal(D.read(s).horloge.heures,9);});
test('espaces séparés : Monde utilise le moteur de fiche sans écrire la fiche',()=>{assert.equal(C.create,F.create);assert.equal(F.read(attrs(empty)),null);assert.ok(Object.keys(C.pack(C.flatten(empty))).every(n=>n.startsWith('owd_monde_p_')));});
test('une frappe non envoyée survit à une réception',()=>{const s=attrs(empty),a=new C.Session(s,empty),b=new C.Session(s,empty),sa=C.copy(empty),sb=C.copy(empty);sa.temperature=17.5;a.capture(sa);sb.horloge=D.advance(sb.horloge,3);b.capture(sb);merge(s,b.outgoing());assert.equal(a.receive(s).state.temperature,17.5);});
test('même champ : convergence, pas de renvoi du conflit en boucle',()=>{let now=1000;const s=attrs(empty),a=new C.Session(s,empty,()=>now),b=new C.Session(s,empty,()=>now);a.capture({...empty,temperature:10});b.capture({...empty,temperature:30});merge(s,a.outgoing());merge(s,b.outgoing());now+=5000;assert.equal(a.receive(s).state.temperature,30);assert.equal(b.receive(s).state.temperature,30);assert.deepEqual(a.outgoing(),{});});
test('écriture perdue : conservée et renvoyée',()=>{let now=1000;const s=attrs(empty),a=new C.Session(s,empty,()=>now);a.capture({...empty,temperature:9});a.outgoing();now+=5000;assert.equal(a.receive(s).state.temperature,9);assert.equal(Object.keys(a.outgoing()).length,1);});
test('activation confirmée avant les registres, anciennes données intactes',()=>{const s={owd_camp_h:'8,520',owd_camp_conf:'{"v":1,"degres":21}'},a=new C.Session(s,D.read(s));a.capture({...D.read(s),temperature:25});assert.deepEqual(Object.keys(a.outgoing()),[C.BASE]);assert.equal(Object.keys(a.outgoing()).length,0);merge(s,{[C.BASE]:{current:JSON.stringify({format:1,state:D.read(s)})}});a.receive(s);merge(s,a.outgoing());assert.equal(D.read(s).temperature,25);assert.equal(s.owd_camp_h,'8,520');});
test('données illisibles ou futures : arrêt, aucune remise à zéro',()=>{assert.throws(()=>D.read({owd_camp_h:'cassé'}));assert.throws(()=>D.read({owd_camp_conf:'{"v":9}'}));assert.throws(()=>D.read(attrs({...empty,v:2})));assert.throws(()=>D.read(attrs({...empty,temperature:'20'})));assert.throws(()=>D.read(attrs({...empty,horloge:{...empty.horloge,secondes:60}})));});
console.log(total+' scénarios Monde validés.');
