'use strict';const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),A=require('../extension/firefox/beta/attack-map.js');
let disposed=0,created=[];class Mesh{constructor(name){this.name=name;this.position={x:0,y:0,z:0};this.renderingGroupId=0;this.alphaIndex=0;this.scaling={x:1,y:1};}static CreatePlane(name){let m=new Mesh(name);created.push(m);return m}setVerticesData(_,p){this.points=p}setIndices(i){this.indices=i}computeWorldMatrix(){}refreshBoundingInfo(){}dispose(){disposed++;this.dead=true}}
class Shader{constructor(){}getClassName(){return 'ShaderMaterial'}setArray4(_,color){this.color=color}dispose(){}}
function gridMesh(radius=40){let m=new Mesh('Hex-Grid-Line-System'),pts=[],ids=[];for(let q=-8;q<9;q++)for(let r=-8;r<9;r++){let g={radius:radius/.98,flat:true},c=A.basis({radius,flat:true},q,r),p=A.polygon(g,c[0]+11,c[1]+22);for(let i=0;i<6;i++){let a=p[i],b=p[(i+1)%6];let n=pts.length/3;pts.push(a[0],-a[1],0,b[0],-b[1],0);ids.push(n,n+1);}}m.getVerticesData=()=>pts;m.getIndices=()=>ids;m.position.z=9999990;return m;}
let tok={id:'t1',attributes:{layer:'objects',controlledby:'all',left:11,top:22,statusmarkers:'red@2'},get(k){return this.attributes[k]},save(d){Object.assign(this.attributes,d)}};
let col={models:[tok],get:()=>tok},pg={id:'p1',thegraphics:col,get(k){return {showgrid:true,grid_type:'hexr',snapping_increment:1,width:20,height:20}[k]}},pos={x:71,y:82},node={isEnabled:()=>true,getAbsolutePosition:()=>pos};
let window={currentPlayer:{id:'p1',d20:{engine:{tabletopSelected:()=>[{model:tok}]}}},Campaign:{activePage:()=>pg},is_gm:false,MeshScene:{meshes:[gridMesh(),new Mesh('token')],materials:[new Shader()],getTransformNodeByName:()=>node},addEventListener(){}};let tick;
let context={window,Campaign:window.Campaign,btoa,atob,Number,Math,Date,JSON,Proxy,setInterval:f=>(tick=f,1),clearInterval(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){},document:{},console};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../extension/firefox/beta/attack-map.js'),'utf8'),context);
let source={},p={mirror:false,orientation:0,path:[[0,-1,'pass'],[0,-6,'hit']],owner:'test',expiresAt:Date.now()+8000};window.OwdAttackMap.preview(source,{preview:p,sequence:1});tick();assert.equal(created.length,2);assert.equal(window.__owdAttackMapState.cells[0].cells[1].r,-6);assert.ok(created.every(m=>!m.isPickable&&m.points.length===36&&m.indices.length===36));let centre=window.__owdAttackMapState.cells[0].cells[1];assert.ok(Math.abs(centre.x-11)<.01);assert.ok(Math.abs(centre.y-(22-6*Math.sqrt(3)*40))<.01);assert.deepEqual(Array.from(created[1].material.color),[1,215/255,127/255,1]);assert.deepEqual(Array.from(created[0].material.color),[103/255,91/255,65/255,1]);assert.ok(created.every(m=>m.material.alpha===1));assert.equal(created[0].position.z,9999988);console.log('OK Jumpgate : origine au centre malgré marqueurs décalés, contours opaques creux, couleurs de fiche et profondeur de grille');
node.isEnabled=()=>false;context.requestAnimationFrame=()=>null; // Drive the scheduled frame by saving callback in the next fixture.
window.OwdAttackMap.preview(source,{action:'stop',owner:'test',sequence:2});assert.equal(tok.attributes.statusmarkers,'red@2');let tag=A.encode({...p,owner:'other'});tok.attributes.statusmarkers='red@2,'+tag;window.OwdAttackMap.preview(source,{action:'stop',owner:'test',sequence:1});assert.equal(tok.attributes.statusmarkers,'red@2,'+tag);console.log('OK retrait ciblé et ancien stop incapable d’effacer le marqueur d’autrui');
window.OwdAttackMap.preview(source,{preview:p,sequence:1});assert.equal(tok.attributes.statusmarkers,'red@2,'+tag);console.log('OK heartbeat ancien ignoré après arrêt');
