/* Transferts : données complètes, reprise d'une réception partielle, conflits
 * et confirmations serveur. Aucune API Roll20 ni dépendance externe. */
'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),D=require('../docs/javascripts/owd-inventaire-data.js'),C=require('../docs/javascripts/owd-sync.js');
let count=0;function test(label,fn){fn();count++;console.log('OK '+label);}
const original=[{ref:'bag',nom:'Sac',contenant:'liquide',qte:1,img:'https://example.invalid/sac.png',desc:'Été',arme:null,ou:'sac',emp:-1,dans:'',extras:{marque:'personnelle'}},{ref:'water',nom:'Eau',contenu:'liquide',dans:'bag',qte:3,ou:'sac',emp:-1},{ref:'weapon',nom:'Épée',qte:1,arme:{attaque:'2+3',modsDegats:['Force','Dexterite',''],comp:'c1'},ou:'mainG',emp:2,dans:''}];
const job=D.prepare('a','b',D.group({objets:original},'bag'),'test1');
test('conteneur et contenu copiés, références et liens internes remappés',()=>{assert.equal(job.dest.length,2);assert.equal(job.dest[1].dans,job.dest[0].ref);assert.notEqual(job.dest[0].ref,'bag');assert.deepEqual(job.dest[0].extras,original[0].extras);assert.equal(job.dest[0].img,original[0].img);assert.deepEqual(job.items,original.slice(0,2));assert.equal(original[1].dans,'bag');});
test('boucle de conteneurs bornée et objet absent refusé',()=>{assert.equal(D.group({objets:[{ref:'a',dans:'b'},{ref:'b',dans:'a'}]},'a').length,2);assert.throws(()=>D.group({objets:[]},'missing'));});
test('personnages identiques et références dupliquées refusés',()=>{assert.throws(()=>D.prepare('a','a',original,'x'));assert.throws(()=>D.prepare('a','b',[original[0],original[0]],'x'));});
test('armes, trois MOD et métadonnées conservés hors placement',()=>{const j=D.prepare('a','b',[original[2]],'test2');assert.deepEqual(j.dest[0].arme,original[2].arme);assert.equal(j.dest[0].ou,'sac');assert.equal(j.dest[0].emp,-1);});
function api(state){const ctx={state:D.copy(state),window:{OwdInventoryData:D},save(){ctx.saves++;},remount(){},invSelectionLocale:'',saves:0};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/fiche/equipement/inv-transfert.js'),'utf8'),ctx);return ctx;}
test('réception rejouable après un envoi partiel, un seul exemplaire',()=>{const b=api({inv:{objets:[{ref:job.dest[0].ref,nom:'Sac'}]}});b.importeTransfert(job);b.importeTransfert(job);assert.equal(b.state.inv.objets.length,2);assert.ok(D.received(b.state,job));});
test('reçu durable empêche de recréer un objet retiré après réception',()=>{const b=api({inv:{objets:[]}});b.importeTransfert(job);b.confirmeTransfert(job);b.state.inv.objets=[];b.importeTransfert(job);assert.equal(b.state.inv.objets.length,0);assert.ok(D.committed(b.state,job));});
test('retrait source idempotent, autres objets intacts',()=>{const a=api({inv:{objets:original}});a.retireTransfert(job);a.retireTransfert(job);assert.ok(D.removed(a.state,job));assert.deepEqual(JSON.parse(JSON.stringify(a.state.inv.objets)),[original[2]]);});
test('modification concurrente source protège tous les objets du transfert',()=>{const a=api({inv:{objets:original}});a.state.inv.objets[1].qte=4;assert.throws(()=>a.retireTransfert(job),/modifié/);assert.equal(a.state.inv.objets.length,3);assert.equal(a.saves,0);});
test('annulation du reçu intact sans toucher les autres objets',()=>{const b=api({inv:{objets:job.dest.concat([original[2]])}});b.annuleTransfert(job);assert.ok(D.cancelled(b.state,job));assert.equal(b.state.inv.objets[0].ref,'weapon');});
test('annulation ne supprime jamais un reçu modifié ailleurs',()=>{const b=api({inv:{objets:job.dest}});b.state.inv.objets[0].desc='Retouché';assert.throws(()=>b.annuleTransfert(job),/modifié/);assert.equal(b.state.inv.objets.length,2);assert.equal(b.saves,0);});
test('photographie locale et réception partielle ne valent pas confirmation',()=>{const state={v:11,inv:{objets:[]}},attrs={[C.BASE]:{current:JSON.stringify({format:1,state}),max:''}},s=new C.Session(attrs,state);const next=D.copy(state);next.inv.objets=job.dest;s.capture(next);const outgoing=s.outgoing();assert.ok(!D.received(C.read(attrs).state,job));const first=Object.keys(outgoing)[0];attrs[first]=outgoing[first];assert.ok(!D.received(C.read(attrs).state,job));Object.assign(attrs,outgoing);assert.ok(D.received(C.read(attrs).state,job));assert.ok(!D.committed(C.read(attrs).state,job));});
console.log(count+' scénarios de transfert validés.');
